version: '3.8'

x-common: &common
  networks:
    - my-network
  environment:
    - RABBITMQ_URL=amqp://user:password@rabbitmq:5672
  depends_on:
    - rabbitmq

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    networks:
      - my-network

  producer:
    build:
      context: ./producer
      dockerfile: Dockerfile.prod
    ports:
      - 3001:3001
    <<: *common

  consumer:
    build:
      context: ./consumer
      dockerfile: Dockerfile.prod
    ports:
      - 3002:3002
    <<: *common

networks:
  my-network:
    driver: bridge