version: '3.8'

x-common: &common
  networks:
    - my-network
  environment:
    - RABBITMQ_URL=amqp://user:password@rabbitmq:5672
  depends_on:
    - rabbitmq
  command: yarn start:dev
  restart: always


services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    networks:
      - my-network

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:8080
    environment:
      - server.port=8080
      - eureka.client.service-url.defaultZone=http://netflixeureka:8761/eureka
      - spring.application.name=gateway
    networks:
      - my-network

  producer:
    build:
      context: ./producer
      dockerfile: Dockerfile.dev
    ports:
      - 3001:3001
    volumes:
      - /app/node_modues
      - ./producer/src:/app/src
    <<: *common

  consumer:
    build:
      context: ./consumer
      dockerfile: Dockerfile.dev
    ports:
      - 3002:3002
    volumes:
      - /app/node_modues
      - ./consumer/src:/app/src
    <<: *common

networks:
  my-network:
    driver: bridge
